name: flutter_github_client
description: Flutter git hub client.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  flutter_riverpod: ^0.12.4
  flutter_state_notifier: ^0.7.0

  # Network
  graphql_flutter: ^3.1.0
  data_connection_checker: ^0.3.4

  # Web
  webview_flutter: ^2.0.4

  # Model
  freezed_annotation:

  # key value local storage
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^0.5.12

  # l10n
  intl: ^0.17.0

  # Util
  device_info: ^2.0.0
  logger: ^1.0.0
  package_info: ^2.0.0
  enum_to_string: ^2.0.1

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2

  # Linter
  pedantic_mono: ^1.11.0

  # code generator
  flutter_gen: ^2.0.3
  artemis: ^5.1.0

  # l10n
  intl_translation: ^0.17.0

  # Test
  mockito: ^4.1.4

  # Launcher Icons
  flutter_launcher_icons: ^0.8.1

  # UI
  flutter_native_splash: ^0.3.2

  # Model
  freezed: ^0.12.2
  json_serializable: ^3.5.1

flutter_gen:
  output: lib/generated/
  lineLength: 80

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter_native_splash:
  image: assets/images/logo.png
  color: "fff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  intl: any
  analyzer: ^0.41.1